# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\client_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Client_Main_Window(object):
    def setupUi(self, Client_Main_Window):
        Client_Main_Window.setObjectName("Client_Main_Window")
        Client_Main_Window.resize(800, 600)
        Client_Main_Window.setMinimumSize(QtCore.QSize(800, 600))
        Client_Main_Window.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.centralwidget = QtWidgets.QWidget(Client_Main_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget_contacts = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_contacts.setGeometry(QtCore.QRect(20, 40, 231, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget_contacts.setFont(font)
        self.tableWidget_contacts.setToolTip("")
        self.tableWidget_contacts.setObjectName("tableWidget_contacts")
        self.tableWidget_contacts.setColumnCount(2)
        self.tableWidget_contacts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_contacts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_contacts.setHorizontalHeaderItem(1, item)
        self.label_contacts_list = QtWidgets.QLabel(self.centralwidget)
        self.label_contacts_list.setGeometry(QtCore.QRect(30, 10, 221, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_contacts_list.setFont(font)
        self.label_contacts_list.setAlignment(QtCore.Qt.AlignCenter)
        self.label_contacts_list.setObjectName("label_contacts_list")
        self.btn_Add_contact = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Add_contact.setGeometry(QtCore.QRect(20, 522, 115, 45))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Add_contact.setFont(font)
        self.btn_Add_contact.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(255, 196, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_Add_contact.setObjectName("btn_Add_contact")
        self.btn_Delete_contact = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Delete_contact.setGeometry(QtCore.QRect(144, 522, 111, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Delete_contact.setFont(font)
        self.btn_Delete_contact.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(255, 5, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_Delete_contact.setObjectName("btn_Delete_contact")
        self.btn_clear_textEdit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_textEdit.setGeometry(QtCore.QRect(290, 520, 91, 45))
        self.btn_clear_textEdit.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(255, 5, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_clear_textEdit.setObjectName("btn_clear_textEdit")
        self.btn_Send_new_message = QtWidgets.QPushButton(self.centralwidget)
        self.btn_Send_new_message.setGeometry(QtCore.QRect(544, 520, 231, 45))
        self.btn_Send_new_message.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(55, 255, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.btn_Send_new_message.setObjectName("btn_Send_new_message")
        self.text_History_message = QtWidgets.QLabel(self.centralwidget)
        self.text_History_message.setGeometry(QtCore.QRect(280, 40, 501, 371))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.text_History_message.setFont(font)
        self.text_History_message.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.text_History_message.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.text_History_message.setObjectName("text_History_message")
        self.textEdit_new_message = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_new_message.setGeometry(QtCore.QRect(283, 450, 501, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEdit_new_message.setFont(font)
        self.textEdit_new_message.setObjectName("textEdit_new_message")
        self.label_history_m = QtWidgets.QLabel(self.centralwidget)
        self.label_history_m.setGeometry(QtCore.QRect(290, 10, 131, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_history_m.setFont(font)
        self.label_history_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_history_m.setObjectName("label_history_m")
        self.label_new_message = QtWidgets.QLabel(self.centralwidget)
        self.label_new_message.setGeometry(QtCore.QRect(400, 420, 201, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_new_message.setFont(font)
        self.label_new_message.setAlignment(QtCore.Qt.AlignCenter)
        self.label_new_message.setObjectName("label_new_message")
        Client_Main_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Client_Main_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        Client_Main_Window.setMenuBar(self.menubar)
        self.action_2 = QtWidgets.QAction(Client_Main_Window)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(Client_Main_Window)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(Client_Main_Window)
        self.action_4.setObjectName("action_4")
        self.menu.addSeparator()
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Client_Main_Window)
        self.btn_clear_textEdit.clicked.connect(self.textEdit_new_message.clear)
        QtCore.QMetaObject.connectSlotsByName(Client_Main_Window)

    def retranslateUi(self, Client_Main_Window):
        _translate = QtCore.QCoreApplication.translate
        Client_Main_Window.setWindowTitle(_translate("Client_Main_Window", "Чат.  Клиент Мессенджер"))
        item = self.tableWidget_contacts.horizontalHeaderItem(0)
        item.setText(_translate("Client_Main_Window", "№ id"))
        item = self.tableWidget_contacts.horizontalHeaderItem(1)
        item.setText(_translate("Client_Main_Window", "Имя контакта"))
        self.label_contacts_list.setText(_translate("Client_Main_Window", "Список контактов"))
        self.btn_Add_contact.setText(_translate("Client_Main_Window", "Добавить контакт"))
        self.btn_Delete_contact.setText(_translate("Client_Main_Window", "Удалить контакт"))
        self.btn_clear_textEdit.setText(_translate("Client_Main_Window", "Очистить поле"))
        self.btn_Send_new_message.setText(_translate("Client_Main_Window", "Отправить сообщение"))
        self.text_History_message.setText(_translate("Client_Main_Window", "TextLabel"))
        self.textEdit_new_message.setHtml(_translate("Client_Main_Window", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">прпорпорппппппппппппп</p></body></html>"))
        self.label_history_m.setText(_translate("Client_Main_Window", "История сообщений"))
        self.label_new_message.setText(_translate("Client_Main_Window", "Введите новое сообщение:"))
        self.menu.setTitle(_translate("Client_Main_Window", "Файл"))
        self.menu_2.setTitle(_translate("Client_Main_Window", "Контакты"))
        self.action_2.setText(_translate("Client_Main_Window", "Открыть"))
        self.action_3.setText(_translate("Client_Main_Window", "Сохранить"))
        self.action_4.setText(_translate("Client_Main_Window", "Добавить контакт"))
    
    
    def show_history_message(self):
        # when DoubleClick is clicked to contact
        # show_history_message for items(contact)
        pass
    
    def send_message(self):
        # when push btn_Send_new_message
        # send message from clien to contact
        pass
    
    def add_contact(self, new_contact):
        # when push btn_Add_contact
        # add_contact to contact_list
        pass        
    
    def delete_contact(self, contact):
        # when push btn_Delete_contact
        # add_contact to contact_list
        pass  

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Client_Main_Window = QtWidgets.QMainWindow()
    ui = Ui_Client_Main_Window()
    ui.setupUi(Client_Main_Window)
    Client_Main_Window.show()
    sys.exit(app.exec_())
